format compact; clear; clc % World Temperatures
% Place data in same directory as this script
Data = readtable('4 Temperature Deviation.txt', ...
    'Delimiter', {' ','\t', ','}, ...
    'MultipleDelimsAsOne', true, ...
    'VariableNamesLine', 6, 'NumHeaderLines', 7, ...
    'LeadingDelimitersRule', 'ignore')

